[supabase]

url = "https://bddsrsaatvtjnccbwxim.supabase.co"
key= "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkZHNyc2FhdHZ0am5jY2J3eGltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMDM0MjQsImV4cCI6MjA2NDY3OTQyNH0.lkToaG8DZvezYlSp6fLuLbix8nnhSIGaALcOs0XWpNk"